### ISSUE TITLE
Reproducibility problems with `proto-build`

### ISSUE THREAD

**Issue by tony-iqlusion** [cosmos/cosmos-rust#15]
I've pushed up a branch containing the files changed when I run `proto-build` locally:

https://github.com/cosmos/cosmos-rust/pull/16/files

It appears to be mostly whitespace changes. I'm not sure what the cause would be.

This change to `cosmos.base.abci.v1beta1.rs` in particular (edit: actually a few files) looks pretty strange:

https://github.com/cosmos/cosmos-rust/pull/16/files#diff-7380925ee3d5ab57486392d57f665066eaafd2b93b062a8dcdac1b6fa301839cR98

```
-    pub header: ::std::option::Option<tendermint_proto::types::Header>,
+    pub header: ::std::option::Option<super::super::super::tendermint::types::Header>,
```

For whatever reason it's outputting `super::super::super::tendermint` instead of `tendermint_proto`.

**Comment by tony-iqlusion** [comment]
I'd like to try enabling `rustfmt` on the output. I think that'd not only make it more reproducible, but also more readable.

**Comment by jkilpatr** [comment]
So I made that has a hand edit. I'm not sure why the builder is so insistent on that super::super pattern. I think it comes from how things are referenced in the proto scope, which isn't relevant in our case since we have tendermint_proto as a flat dependency coming in from crates.io. I'm not sure there's much we can do to solve this in place, but we might be able to find/replace in the file as we generate it.
