### ISSUE TITLE
MsgTransfer does not impl TypeUrl

### ISSUE THREAD

**Issue by Magicloud** [cosmos/cosmos-rust#295]
`MsgTransfer` impl-s `MessageExt`, the function `from_any` of which requires impl of `TypeUrl`.

Not sure if this is on purpose, right now with 0.14.0, I cannot do `MsgTransfer::from_any`.

**Comment by tony-iqlusion** [comment]
For now we maintain a manual registry of type URLs. It's found here:

https://github.com/cosmos/cosmos-rust/blob/main/cosmos-sdk-proto/src/type_urls.rs

Feel free to submit a PR to add one, or otherwise I'll take a look at this when I have time.

Hopefully the next release of `prost` will populate them automatically.

**Comment by Magicloud** [comment]
> 

Ah, I am not exactly sure the url for MsgTransfer.
